### ISSUE TITLE
Scrolling issue in log view

### ISSUE THREAD

**Issue by idoco** [loadmill/loadmill-desktop-agent#4]
When scrolling down, the top view disappears 

https://user-images.githubusercontent.com/5776439/205482014-d49bf550-4323-48b7-85b6-b7e2458abd0f.mov

**Comment by Gilad-Gur-Andelman** [comment]
Good one. Probably a regression after the dark theme change. Thanks

**Comment by Gilad-Gur-Andelman** [comment]
I can't reproduce this bug. What version do you run?

**Comment by Gilad-Gur-Andelman** [comment]
solved
